name: generate coverage badge

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          cache: 'pip'
          python-version: '3.9'
          cache-dependency-path: './requirements.txt'
          
      - name: 환경 설정
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: 패키지 확인
        run: pip list

      - name: 테스트 실행
        run: pytest --cov=calculator --junitxml=reports/junit/junit.xml --html=reports/junit/report.html

      - name: 배지 생성
        run: |
          genbadge tests
          genbadge coverage

      - name: 변경 사항 출력 및 적용
        run: |
          git status
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "변경 사항 적용"
          
      - name: 변경 사항 push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true

