name: generate coverage badge

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          cache: 'pip'
          python-version: '3.9'
          cache-dependency-path: './requirements.txt'
          
      - name: 환경 설정
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: 패키지 확인
        run: pip list

      - name: 테스트 실행
        run: pytest --cov=calculator --junitxml=reports/junit/junit.xml --html=reports/junit/report.html

      - name: 배지 생성
        run: genbadge tests
